In [1]:
using DataFrames

train = readtable("data/train.csv")
test = readtable("data/test.csv")

367×12 DataFrames.DataFrame
│ Row │ Loan_ID    │ Gender   │ Married │ Dependents │ Education      │
├─────┼────────────┼──────────┼─────────┼────────────┼────────────────┤
│ 1   │ "LP001015" │ "Male"   │ "Yes"   │ "0"        │ "Graduate"     │
│ 2   │ "LP001022" │ "Male"   │ "Yes"   │ "1"        │ "Graduate"     │
│ 3   │ "LP001031" │ "Male"   │ "Yes"   │ "2"        │ "Graduate"     │
│ 4   │ "LP001035" │ "Male"   │ "Yes"   │ "2"        │ "Graduate"     │
│ 5   │ "LP001051" │ "Male"   │ "No"    │ "0"        │ "Not Graduate" │
│ 6   │ "LP001054" │ "Male"   │ "Yes"   │ "0"        │ "Not Graduate" │
│ 7   │ "LP001055" │ "Female" │ "No"    │ "1"        │ "Not Graduate" │
│ 8   │ "LP001056" │ "Male"   │ "Yes"   │ "2"        │ "Not Graduate" │
│ 9   │ "LP001059" │ "Male"   │ "Yes"   │ "2"        │ "Graduate"     │
│ 10  │ "LP001067" │ "Male"   │ "No"    │ "0"        │ "Not Graduate" │
│ 11  │ "LP001078" │ "Male"   │ "No"    │ "0"        │ "Not Graduate" │
⋮
│ 356 │ "LP002932" │ "Male"   │ "Yes"   │ "3+"       │ "Graduate"     │
│ 357 │ "LP002935" │ "Male"   │ "Yes"   │ "1"        │ "Graduate"     │
│ 358 │ "LP002952" │ "Male"   │ "No"    │ "0"        │ "Graduate"     │
│ 359 │ "LP002954" │ "Male"   │ "Yes"   │ "2"        │ "Not Graduate" │
│ 360 │ "LP002962" │ "Male"   │ "No"    │ "0"        │ "Graduate"     │
│ 361 │ "LP002965" │ "Female" │ "Yes"   │ "0"        │ "Graduate"     │
│ 362 │ "LP002969" │ "Male"   │ "Yes"   │ "1"        │ "Graduate"     │
│ 363 │ "LP002971" │ "Male"   │ "Yes"   │ "3+"       │ "Not Graduate" │
│ 364 │ "LP002975" │ "Male"   │ "Yes"   │ "0"        │ "Graduate"     │
│ 365 │ "LP002980" │ "Male"   │ "No"    │ "0"        │ "Graduate"     │
│ 366 │ "LP002986" │ "Male"   │ "Yes"   │ "0"        │ "Graduate"     │
│ 367 │ "LP002989" │ "Male"   │ "No"    │ "0"        │ "Graduate"     │

│ Row │ Self_Employed │ ApplicantIncome │ CoapplicantIncome │ LoanAmount │
├─────┼───────────────┼─────────────────┼───────────────────┼────────────┤
│ 1   │ "No"          │ 5720            │ 0                 │ 110        │
│ 2   │ "No"          │ 3076            │ 1500              │ 126        │
│ 3   │ "No"          │ 5000            │ 1800              │ 208        │
│ 4   │ "No"          │ 2340            │ 2546              │ 100        │
│ 5   │ "No"          │ 3276            │ 0                 │ 78         │
│ 6   │ "Yes"         │ 2165            │ 3422              │ 152        │
│ 7   │ "No"          │ 2226            │ 0                 │ 59         │
│ 8   │ "No"          │ 3881            │ 0                 │ 147        │
│ 9   │ NA            │ 13633           │ 0                 │ 280        │
│ 10  │ "No"          │ 2400            │ 2400              │ 123        │
│ 11  │ "No"          │ 3091            │ 0                 │ 90         │
⋮
│ 356 │ "No"          │ 7603            │ 1213              │ 197        │
│ 357 │ "No"          │ 3791            │ 1936              │ 85         │
│ 358 │ "No"          │ 2500            │ 0                 │ 60         │
│ 359 │ "No"          │ 3132            │ 0                 │ 76         │
│ 360 │ "No"          │ 4000            │ 2667              │ 152        │
│ 361 │ "No"          │ 8550            │ 4255              │ 96         │
│ 362 │ "No"          │ 2269            │ 2167              │ 99         │
│ 363 │ "Yes"         │ 4009            │ 1777              │ 113        │
│ 364 │ "No"          │ 4158            │ 709               │ 115        │
│ 365 │ "No"          │ 3250            │ 1993              │ 126        │
│ 366 │ "No"          │ 5000            │ 2393              │ 158        │
│ 367 │ "Yes"         │ 9200            │ 0                 │ 98         │

│ Row │ Loan_Amount_Term │ Credit_History │ Property_Area │
├─────┼──────────────────┼────────────────┼───────────────┤
│ 1   │ 360              │ 1              │ "Urban"       │
│ 2   │ 360              │ 1              │ "Urban"       │
│ 3   │ 360              │ 1              │ "Urban"       │
│ 4   │ 360              │ NA             │ "Urban"       │
│ 5   │ 360              │ 1              │ "Urban"       │
│ 6   │ 360              │ 1              │ "Urban"       │
│ 7   │ 360              │ 1              │ "Semiurban"   │
│ 8   │ 360              │ 0              │ "Rural"       │
│ 9   │ 240              │ 1              │ "Urban"       │
│ 10  │ 360              │ 1              │ "Semiurban"   │
│ 11  │ 360              │ 1              │ "Urban"       │
⋮
│ 356 │ 360              │ 1              │ "Urban"       │
│ 357 │ 360              │ 1              │ "Urban"       │
│ 358 │ 360              │ 1              │ "Urban"       │
│ 359 │ 360              │ NA             │ "Rural"       │
│ 360 │ 360              │ 1              │ "Semiurban"   │
│ 361 │ 360              │ NA             │ "Urban"       │
│ 362 │ 360              │ 1              │ "Semiurban"   │
│ 363 │ 360              │ 1              │ "Urban"       │
│ 364 │ 360              │ 1              │ "Urban"       │
│ 365 │ 360              │ NA             │ "Semiurban"   │
│ 366 │ 360              │ 1              │ "Rural"       │
│ 367 │ 180              │ 1              │ "Rural"       │

In [2]:
size(train)

(614, 13)

In [3]:
names(train)

13-element Array{Symbol,1}:
 :Loan_ID
 :Gender
 :Married
 :Dependents
 :Education
 :Self_Employed
 :ApplicantIncome
 :CoapplicantIncome
 :LoanAmount
 :Loan_Amount_Term
 :Credit_History
 :Property_Area
 :Loan_Status

In [4]:
head(train, 5)

5×13 DataFrames.DataFrame
│ Row │ Loan_ID    │ Gender │ Married │ Dependents │ Education      │
├─────┼────────────┼────────┼─────────┼────────────┼────────────────┤
│ 1   │ "LP001002" │ "Male" │ "No"    │ "0"        │ "Graduate"     │
│ 2   │ "LP001003" │ "Male" │ "Yes"   │ "1"        │ "Graduate"     │
│ 3   │ "LP001005" │ "Male" │ "Yes"   │ "0"        │ "Graduate"     │
│ 4   │ "LP001006" │ "Male" │ "Yes"   │ "0"        │ "Not Graduate" │
│ 5   │ "LP001008" │ "Male" │ "No"    │ "0"        │ "Graduate"     │

│ Row │ Self_Employed │ ApplicantIncome │ CoapplicantIncome │ LoanAmount │
├─────┼───────────────┼─────────────────┼───────────────────┼────────────┤
│ 1   │ "No"          │ 5849            │ 0.0               │ NA         │
│ 2   │ "No"          │ 4583            │ 1508.0            │ 128        │
│ 3   │ "Yes"         │ 3000            │ 0.0               │ 66         │
│ 4   │ "No"          │ 2583            │ 2358.0            │ 120        │
│ 5   │ "No"          │ 6000            │ 0.0               │ 141        │

│ Row │ Loan_Amount_Term │ Credit_History │ Property_Area │ Loan_Status │
├─────┼──────────────────┼────────────────┼───────────────┼─────────────┤
│ 1   │ 360              │ 1              │ "Urban"       │ "Y"         │
│ 2   │ 360              │ 1              │ "Rural"       │ "N"         │
│ 3   │ 360              │ 1              │ "Urban"       │ "Y"         │
│ 4   │ 360              │ 1              │ "Urban"       │ "Y"         │
│ 5   │ 360              │ 1              │ "Urban"       │ "Y"         │

In [5]:
# Provides count length, mean, median, minimum, quartiles and max
describe(train[:Property_Area])

Summary Stats:
Length:         614
Type:           String
Number Unique:  3
Number Missing: 0
% Missing:      0.000000

In [6]:
?describe()

```
describe(a)
```

Pretty-print the summary statistics provided by [`summarystats`](@ref): the mean, minimum, 25th percentile, median, 75th percentile, and maximum.

Summarize the columns of an AbstractDataFrame

```julia
describe(df::AbstractDataFrame)
describe(io, df::AbstractDataFrame)
```

**Arguments**

  * `df` : the AbstractDataFrame
  * `io` : optional output descriptor

**Result**

  * nothing

**Details**

If the column's base type derives from Number, compute the minimum, first quantile, median, mean, third quantile, and maximum. NA's are filtered and reported separately.

For boolean columns, report trues, falses, and NAs.

For other types, show column characteristics and number of NAs.

**Examples**

```julia
df = DataFrame(i = 1:10, x = rand(10), y = rand(["a", "b", "c"], 10))
describe(df)
```

In [7]:
countmap(train[:LoanAmount])

Dict{Union{DataArrays.NAtype, Int64},Int64} with 204 entries:
  158 => 6
  134 => 4
  160 => 12
  131 => 4
  207 => 1
  300 => 1
  173 => 3
  201 => 2
  74  => 3
  176 => 2
  490 => 1
  70  => 8
  114 => 2
  165 => 3
  96  => 9
  133 => 5
  84  => 4
  230 => 1
  117 => 1
  93  => 3
  50  => 4
  80  => 6
  311 => 1
  188 => 3
  132 => 7
  ⋮   => ⋮

In [8]:
?countmap()

```
countmap(x)
```

Return a dictionary mapping each unique value in `x` to its number of occurrences.

In [17]:
! Pkg.add("StatPlots")

INFO: Cloning cache of DataValues from https://github.com/davidanthoff/DataValues.jl.git
INFO: Cloning cache of IterableTables from https://github.com/davidanthoff/IterableTables.jl.git
INFO: Cloning cache of NamedTuples from https://github.com/blackrock/NamedTuples.jl.git
INFO: Cloning cache of StatPlots from https://github.com/JuliaPlots/StatPlots.jl.git
INFO: Cloning cache of TableTraits from https://github.com/davidanthoff/TableTraits.jl.git
INFO: Cloning cache of TableTraitsUtils from https://github.com/davidanthoff/TableTraitsUtils.jl.git
INFO: Installing DataValues v0.3.0
INFO: Installing IterableTables v0.5.2
INFO: Installing NamedTuples v4.0.0
INFO: Installing StatPlots v0.5.1
INFO: Installing TableTraits v0.0.1
INFO: Installing TableTraitsUtils v0.1.0
INFO: Building SpecialFunctions
INFO: Building Rmath
INFO: Building Plots
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of StatPlots
INFO: Use `Pkg.update()` to get the latest versions of your packages

LoadError: MethodError: no method matching !(::Void)
Closest candidates are:
  !(::Base.##771#772) at deprecated.jl:852
  !(::Bool) at bool.jl:36
  !(::Function) at operators.jl:904
  ...

In [18]:
! Pkg.add("PyPlot")

INFO: Cloning cache of LaTeXStrings from https://github.com/stevengj/LaTeXStrings.jl.git
INFO: Cloning cache of PyCall from https://github.com/JuliaPy/PyCall.jl.git
INFO: Cloning cache of PyPlot from https://github.com/JuliaPy/PyPlot.jl.git
INFO: Installing LaTeXStrings v0.3.0
INFO: Installing PyCall v1.15.0
INFO: Installing PyPlot v2.3.2
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using python (Python 3.6.1) at /home/deeplearn/anaconda3/bin/python, libpython = /home/deeplearn/anaconda3/lib/libpython3.6m
INFO: /home/deeplearn/.julia/v0.6/PyCall/deps/deps.jl has been updated
INFO: /home/deeplearn/.julia/v0.6/PyCall/deps/PYTHON has been updated
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of PyPlot
INFO: Use `Pkg.update()` to get the latest versions of your packages

LoadError: MethodError: no method matching !(::Void)
Closest candidates are:
  !(::Base.##771#772) at deprecated.jl:852
  !(::Bool) at bool.jl:36
  !(::Function) at operators.jl:904
  ...

In [9]:
using Plots, StatPlots
pyplot()
Plots.histogram(dropna(train[:ApplicantIncome]),bins=50,xlabel="ApplicantIncome",labels="Frequency")

INFO: Recompiling stale cache file /home/deeplearn/.julia/lib/v0.6/ColorTypes.ji for module ColorTypes.
INFO: Recompiling stale cache file /home/deeplearn/.julia/lib/v0.6/PlotUtils.ji for module PlotUtils.
INFO: Recompiling stale cache file /home/deeplearn/.julia/lib/v0.6/PlotThemes.ji for module PlotThemes.
INFO: Recompiling stale cache file /home/deeplearn/.julia/lib/v0.6/TableTraits.ji for module TableTraits.
INFO: Recompiling stale cache file /home/deeplearn/.julia/lib/v0.6/IterableTables.ji for module IterableTables.
INFO: Recompiling stale cache file /home/deeplearn/.julia/lib/v0.6/LineSearches.ji for module LineSearches.
INFO: Recompiling stale cache file /home/deeplearn/.julia/lib/v0.6/KernelDensity.ji for module KernelDensity.
WARNING: StatsBase.WeightVec is deprecated, use StatsBase.Weights{#1#S, #2#T, #3#V} where #3#V<:AbstractArray{#2#T, 1} where #2#T<:Real where #1#S<:Real instead.
  likely near /home/deeplearn/.julia/v0.6/KernelDensity/src/univariate.jl:80
INFO: Recompiling stale cache file /home/deeplearn/.julia/lib/v0.6/PyCall.ji for module PyCall.
INFO: Recompiling stale cache file /home/deeplearn/.julia/lib/v0.6/PyPlot.ji for module PyPlot.

#### What do you observer in the above?

In [10]:
Plots.boxplot(train[:Education], train[:ApplicantIncome], labels="ApplicantIncome")

####  Do you see the outliers here?

Some are making a lot of money and others remain largely below, with a few folks doing better than the others.

In [11]:
# Plot a histogram and boxplot of Loan amount. We use the knowwn dropna to drop values with no number.
Plots.histogram(dropna(train[:LoanAmount]), bins=50, xlabel="Loan Amount", labels = "Frequency")

In [12]:
 Plots.boxplot(dropna(train[:LoanAmount]), ylabel="LoanAmount")

In [14]:
# Interactive visualization with Plotly
plotly()
Plots.histogram(dropna(train[:ApplicantIncome]),bins=50,xlabel="ApplicantIncome",labels="Frequency")

## Playing with Data

While our exploration of the data, we found a few problems in the data set, which needs to be solved before the data is ready for a good model. This exercise is typically referred as “Data Munging”. Here are the problems, we are already aware of:

- There are missing values for some variables. We should estimate those values wisely depending on a number of missing values and the expected importance of variables.
- While looking at the distributions, we saw that ApplicantIncome and LoanAmount seemed to contain extreme values at either end. Though they might make intuitive sense, but should be treated appropriately.

In addition to these problems with numerical fields, we should also look at the non-numerical fields i.e. Gender, Property_Area, Married, Education and Dependents to see, if they contain any useful information.

In [15]:
# Lets check on some missing values
showcols(train)

614×13 DataFrames.DataFrame
│ Col # │ Name              │ Eltype  │ Missing │
├───────┼───────────────────┼─────────┼─────────┤
│ 1     │ Loan_ID           │ String  │ 0       │
│ 2     │ Gender            │ String  │ 13      │
│ 3     │ Married           │ String  │ 3       │
│ 4     │ Dependents        │ String  │ 15      │
│ 5     │ Education         │ String  │ 0       │
│ 6     │ Self_Employed     │ String  │ 32      │
│ 7     │ ApplicantIncome   │ Int64   │ 0       │
│ 8     │ CoapplicantIncome │ Float64 │ 0       │
│ 9     │ LoanAmount        │ Int64   │ 22      │
│ 10    │ Loan_Amount_Term  │ Int64   │ 14      │
│ 11    │ Credit_History    │ Int64   │ 50      │
│ 12    │ Property_Area     │ String  │ 0       │
│ 13    │ Loan_Status       │ String  │ 0       │

In [16]:
# Replace all the missing values in columns
train[isna.(train[:LoanAmount]),:LoanAmount] = floor(mean(dropna(train[:LoanAmount])))

146.0

### What this does is the following

- `train[:LoanAmount]` accesses LoanAmount column from dataframe
- `isna()` - boolean, meaning it returns a true or flase based on missing column
- `train[condition, :column]` - returns the rows of the given column that satisfy the condition (We'll check that later)
- `dropna()` - ignores NA values
- `mean()` - takes mean
- `floor()` performs the floor operation on the value

In [19]:
?dropna()

```
dropna(v::AbstractVector) -> AbstractVector
```

Return a copy of `v` with all `NA` elements removed.

# Examples

```jldoctest
julia> dropna(@data [NA, 1, NA, 2])
2-element Array{Int64,1}:
 1
 2

julia> dropna([4, 5, 6])
3-element Array{Int64,1}:
 4
 5
 6
```

In [20]:
# We do that for other columns as well...
#replace 0.0 of loan amount with the mean of loan amount 
 train[train[:LoanAmount] .== 0, :LoanAmount] = floor(mean(dropna(train[:LoanAmount])))
 #replace missing gender with mode of gender values
 train[isna.(train[:Gender]), :Gender] = mode(dropna(train[:Gender]))
#replace missing married with mode value  
 train[isna.(train[:Married]), :Married] = mode(dropna(train[:Married])) 
 #replace missing number of dependents with the mode value
 train[isna.(train[:Dependents]),:Dependents]=mode(dropna(train[:Dependents])) 
 #replace missing values of the self_employed column with mode
 train[isna.(train[:Self_Employed]),:Self_Employed]=mode(dropna(train[:Self_Employed])) 
 #replace missing values of loan amount term with mode value
 train[isna.(train[:Loan_Amount_Term]),:Loan_Amount_Term]=mode(dropna(train[:Loan_Amount_Term]))
#replace credit history missing values with mode  
 train[isna.(train[:Credit_History]), :Credit_History] = mode(dropna(train[:Credit_History]))

1

In [21]:
# check again
showcols(train)

614×13 DataFrames.DataFrame
│ Col # │ Name              │ Eltype  │ Missing │
├───────┼───────────────────┼─────────┼─────────┤
│ 1     │ Loan_ID           │ String  │ 0       │
│ 2     │ Gender            │ String  │ 0       │
│ 3     │ Married           │ String  │ 0       │
│ 4     │ Dependents        │ String  │ 0       │
│ 5     │ Education         │ String  │ 0       │
│ 6     │ Self_Employed     │ String  │ 0       │
│ 7     │ ApplicantIncome   │ Int64   │ 0       │
│ 8     │ CoapplicantIncome │ Float64 │ 0       │
│ 9     │ LoanAmount        │ Int64   │ 0       │
│ 10    │ Loan_Amount_Term  │ Int64   │ 0       │
│ 11    │ Credit_History    │ Int64   │ 0       │
│ 12    │ Property_Area     │ String  │ 0       │
│ 13    │ Loan_Status       │ String  │ 0       │

### Ok, this is great!

Next we

In [22]:
# Or we can test
showcols(test)

367×12 DataFrames.DataFrame
│ Col # │ Name              │ Eltype │ Missing │
├───────┼───────────────────┼────────┼─────────┤
│ 1     │ Loan_ID           │ String │ 0       │
│ 2     │ Gender            │ String │ 11      │
│ 3     │ Married           │ String │ 0       │
│ 4     │ Dependents        │ String │ 10      │
│ 5     │ Education         │ String │ 0       │
│ 6     │ Self_Employed     │ String │ 23      │
│ 7     │ ApplicantIncome   │ Int64  │ 0       │
│ 8     │ CoapplicantIncome │ Int64  │ 0       │
│ 9     │ LoanAmount        │ Int64  │ 5       │
│ 10    │ Loan_Amount_Term  │ Int64  │ 6       │
│ 11    │ Credit_History    │ Int64  │ 29      │
│ 12    │ Property_Area     │ String │ 0       │

In [23]:
test[isna.(test[:Gender]), :Gender] = mode(dropna(test[:Gender]));
test[isna.(test[:Dependents]), :Dependents] = mode(dropna(test[:Dependents]));
test[isna.(test[:Self_Employed]), :Self_Employed] = mode(dropna(test[:Self_Employed]));
test[isna.(test[:LoanAmount]), :LoanAmount] = floor(mean(dropna(test[:LoanAmount])));
test[test[:LoanAmount] .== 0, :LoanAmount] = floor(mean(dropna(test[:LoanAmount])));
test[isna.(test[:Loan_Amount_Term]), :Loan_Amount_Term] = mode(dropna(test[:Loan_Amount_Term]));
test[isna.(test[:Credit_History]), :Credit_History] = mode(dropna(test[:Credit_History]));

In [24]:
showcols(test)

367×12 DataFrames.DataFrame
│ Col # │ Name              │ Eltype │ Missing │
├───────┼───────────────────┼────────┼─────────┤
│ 1     │ Loan_ID           │ String │ 0       │
│ 2     │ Gender            │ String │ 0       │
│ 3     │ Married           │ String │ 0       │
│ 4     │ Dependents        │ String │ 0       │
│ 5     │ Education         │ String │ 0       │
│ 6     │ Self_Employed     │ String │ 0       │
│ 7     │ ApplicantIncome   │ Int64  │ 0       │
│ 8     │ CoapplicantIncome │ Int64  │ 0       │
│ 9     │ LoanAmount        │ Int64  │ 0       │
│ 10    │ Loan_Amount_Term  │ Int64  │ 0       │
│ 11    │ Credit_History    │ Int64  │ 0       │
│ 12    │ Property_Area     │ String │ 0       │

In [42]:
Pkg.add("ScikitLearn")

INFO: Cloning cache of Iterators from https://github.com/JuliaCollections/Iterators.jl.git
INFO: Cloning cache of ScikitLearn from https://github.com/cstjean/ScikitLearn.jl.git
INFO: Cloning cache of ScikitLearnBase from https://github.com/cstjean/ScikitLearnBase.jl.git
INFO: Installing Iterators v0.3.1
INFO: Installing ScikitLearn v0.3.0
INFO: Installing ScikitLearnBase v0.3.0
INFO: Building Conda
INFO: Building SpecialFunctions
INFO: Building PyCall
INFO: PyCall is using /home/deeplearn/anaconda3/bin/python (Python 3.6.1) at /home/deeplearn/anaconda3/bin/python, libpython = /home/deeplearn/anaconda3/lib/libpython3.6m
INFO: /home/deeplearn/.julia/v0.6/PyCall/deps/deps.jl has been updated
INFO: /home/deeplearn/.julia/v0.6/PyCall/deps/PYTHON has not changed
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of ScikitLearn
INFO: Use `Pkg.update()` to get the latest versions of your packages

In [50]:
Pkg.update()

INFO: Updating METADATA...
INFO: Updating cache of ColorTypes...
INFO: Updating cache of SHA...
INFO: Updating cache of JSON...
INFO: Computing changes...
INFO: Cloning cache of IteratorInterfaceExtensions from https://github.com/davidanthoff/IteratorInterfaceExtensions.jl.git
INFO: Upgrading ColorTypes: v0.6.5 => v0.6.6
INFO: Installing IteratorInterfaceExtensions v0.0.1
INFO: Upgrading JSON: v0.15.1 => v0.15.2
INFO: Upgrading LineSearches: v3.0.1 => v3.1.0
INFO: Upgrading SHA: v0.5.1 => v0.5.2
INFO: Upgrading TableTraits: v0.0.1 => v0.0.2
WARNING: The following packages have been updated but were already imported:
- ColorTypes
- JSON
- LineSearches
- SHA
- TableTraits
Restart Julia to use the updated versions.

In [25]:
using ScikitLearn: fit!, predict, @sk_import, fit_transform!

@sk_import preprocessing: LabelEncoder
@sk_import model_selection: cross_val_score 
@sk_import metrics: accuracy_score
@sk_import linear_model: LogisticRegression
@sk_import ensemble: RandomForestClassifier
@sk_import tree: DecisionTreeClassifier
@sk_import preprocessing: LabelEncoder

INFO: Recompiling stale cache file /home/deeplearn/.julia/lib/v0.6/ScikitLearn.ji for module ScikitLearn.
WARNING: Method definition count() in module IterTools at deprecated.jl:56 overwritten in module Iterators at deprecated.jl:56.
WARNING: Method definition count(Number) in module IterTools at deprecated.jl:56 overwritten in module Iterators at deprecated.jl:56.
WARNING: Method definition count(Number, Number) in module IterTools at deprecated.jl:56 overwritten in module Iterators at deprecated.jl:56.
WARNING: redefining constant LabelEncoder

PyObject <class 'sklearn.preprocessing.label.LabelEncoder'>

### Label Encoding

In [26]:
labelencoder = LabelEncoder()
categories = [2 3 4 5 6 12 13]

for col in categories
    train[col] = fit_transform!(labelencoder, train[col])
    if col != 13
        test[col] = fit_transform!(labelencoder, test[col])
    end
end

## Build Model

In [27]:
function classification_model(model, predictors)
    y = convert(Array, train[:13])
    X = convert(Array, train[predictors])
    X2 = convert(Array, test[predictors])                 

    #Fit the model:
    fit!(model, X, y)

    #Make predictions on training set:
    predictions = predict(model, X)

    #Print accuracy
    accuracy = accuracy_score(predictions, y)
    println("\naccuracy: ",accuracy)

    #5 fold cross validation
    cross_score = cross_val_score(model, X, y, cv=5)
    
    #print cross_val_score
    println("cross_validation_score: ", mean(cross_score))
    
    #return predictions
    fit!(model, X, y)
    pred = predict(model, X2)
    return pred
end

classification_model (generic function with 1 method)

In [28]:
predictors = [:ApplicantIncome, :CoapplicantIncome, :LoanAmount, :Credit_History, :Loan_Amount_Term, :Gender, :Dependents]

7-element Array{Symbol,1}:
 :ApplicantIncome
 :CoapplicantIncome
 :LoanAmount
 :Credit_History
 :Loan_Amount_Term
 :Gender
 :Dependents

### Logistic Regression

In [29]:
lrmodel = LogisticRegression()
lrpred = classification_model(lrmodel, predictors);

accuracy: 0.8127035830618893
cross_validation_score: 0.8095716552088842

### Decision Tree Classifier

In [31]:
dtmodel = DecisionTreeClassifier()
dtreepred = classification_model(dtmodel, predictors);

accuracy: 1.0
cross_validation_score: 0.7135113696456902

### Random Forest Classifier

In [32]:
rfmodel = RandomForestClassifier(n_estimators=25, min_samples_split=25, max_depth=7, max_features=1, n_jobs=-1)
rfpred = classification_model(rfmodel, predictors);

accuracy: 0.8192182410423453
cross_validation_score: 0.7915917503966157

### Create Submission File

In [35]:
pred = map(x-> if x==1 "Y" else "N" end, lrpred)
outdf = DataFrame(Loan_ID=test[:Loan_ID], Loan_Status=pred)
writetable("data/sub.csv", outdf)

## Adding more stuff

In [37]:
Pkg.add("PyCall.jl")

INFO: Package PyCall is already installed

In [38]:
using PyCall
@pyimport pandas as pd
df = pd.read_csv("data/train.csv")

WARNING: imported binding for df overwritten in module Main

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
10,LP001024,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban,Y
11,LP001027,Male,Yes,2,Graduate,NaN,2500,1840.0,109.0,360.0,1.0,Urban,Y
12,LP001028,Male,Yes,2,Graduate,No,3073,8106.0,200.0,360.0,1.0,Urban,Y
13,LP001029,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural,N
14,LP001030,Male,Yes,2,Graduate,No,1299,1086.0,17.0,120.0,1.0,Urban,Y
15,LP001032,Male,No,0,Graduate,No,4950,0.0,125.0,360.0,1.0,Urban,Y
16,LP001034,Male,No,1,Not Graduate,No,3596,0.0,100.0,240.0,NaN,Urban,Y
17,LP001036,Female,No,0,Graduate,No,3510,0.0,76.0,360.0,0.0,Urban,N
18,LP001038,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural,N
19,LP001041,Male,Yes,0,Graduate,NaN,2600,3500.0,115.0,NaN,1.0,Urban,Y
20,LP001043,Male,Yes,0,Not Graduate,No,7660,0.0,104.0,360.0,0.0,Urban,N
21,LP001046,Male,Yes,1,Graduate,No,5955,5625.0,315.0,360.0,1.0,Urban,Y
22,LP001047,Male,Yes,0,Not Graduate,No,2600,1911.0,116.0,360.0,0.0,Semiurban,N
23,LP001050,NaN,Yes,2,Not Graduate,No,3365,1917.0,112.0,360.0,0.0,Rural,N
24,LP001052,Male,Yes,1,Graduate,NaN,3717,2925.0,151.0,360.0,NaN,Semiurban,N
25,LP001066,Male,Yes,0,Graduate,Yes,9560,0.0,191.0,360.0,1.0,Semiurban,Y
26,LP001068,Male,Yes,0,Graduate,No,2799,2253.0,122.0,360.0,1.0,Semiurban,Y
27,LP001073,Male,Yes,2,Not Graduate,No,4226,1040.0,110.0,360.0,1.0,Urban,Y
28,LP001086,Male,No,0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban,N
29,LP001087,Female,No,2,Graduate,NaN,3750,2083.0,120.0,360.0,1.0,Semiurban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,LP002911,Male,Yes,1,Graduate,No,2787,1917.0,146.0,360.0,0.0,Rural,N
585,LP002912,Male,Yes,1,Graduate,No,4283,3000.0,172.0,84.0,1.0,Rural,N
586,LP002916,Male,Yes,0,Graduate,No,2297,1522.0,104.0,360.0,1.0,Urban,Y
587,LP002917,Female,No,0,Not Graduate,No,2165,0.0,70.0,360.0,1.0,Semiurban,Y
588,LP002925,NaN,No,0,Graduate,No,4750,0.0,94.0,360.0,1.0,Semiurban,Y
589,LP002926,Male,Yes,2,Graduate,Yes,2726,0.0,106.0,360.0,0.0,Semiurban,N
590,LP002928,Male,Yes,0,Graduate,No,3000,3416.0,56.0,180.0,1.0,Semiurban,Y
591,LP002931,Male,Yes,2,Graduate,Yes,6000,0.0,205.0,240.0,1.0,Semiurban,N
592,LP002933,NaN,No,3+,Graduate,Yes,9357,0.0,292.0,360.0,1.0,Semiurban,Y
593,LP002936,Male,Yes,0,Graduate,No,3859,3300.0,142.0,180.0,1.0,Rural,Y
594,LP002938,Male,Yes,0,Graduate,Yes,16120,0.0,260.0,360.0,1.0,Urban,Y
595,LP002940,Male,No,0,Not Graduate,No,3833,0.0,110.0,360.0,1.0,Rural,Y
596,LP002941,Male,Yes,2,Not Graduate,Yes,6383,1000.0,187.0,360.0,1.0,Rural,N
597,LP002943,Male,No,NaN,Graduate,No,2987,0.0,88.0,360.0,0.0,Semiurban,N
598,LP002945,Male,Yes,0,Graduate,Yes,9963,0.0,180.0,360.0,1.0,Rural,Y
599,LP002948,Male,Yes,2,Graduate,No,5780,0.0,192.0,360.0,1.0,Urban,Y
600,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
601,LP002950,Male,Yes,0,Not Graduate,NaN,2894,2792.0,155.0,360.0,1.0,Rural,Y
602,LP002953,Male,Yes,3+,Graduate,No,5703,0.0,128.0,360.0,1.0,Urban,Y
603,LP002958,Male,No,0,Graduate,No,3676,4301.0,172.0,360.0,1.0,Rural,Y
604,LP002959,Female,Yes,1,Graduate,No,12000,0.0,496.0,360.0,1.0,Semiurban,Y
605,LP002960,Male,Yes,0,Not Graduate,No,2400,3800.0,NaN,180.0,1.0,Urban,N
606,LP002961,Male,Yes,1,Graduate,No,3400,2500.0,173.0,360.0,1.0,Semiurban,Y
607,LP002964,Male,Yes,2,Not Graduate,No,3987,1411.0,157.0,360.0,1.0,Rural,Y
608,LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

### Using ggplot2

In [42]:
Pkg.add("RDatasets.jl")

INFO: Cloning cache of RData from https://github.com/JuliaStats/RData.jl.git
INFO: Cloning cache of RDatasets from https://github.com/johnmyleswhite/RDatasets.jl.git
INFO: Installing RData v0.1.0
INFO: Installing RDatasets v0.2.0
INFO: Building SpecialFunctions
INFO: Package database updated

In [41]:
Pkg.add("RCall.jl")

INFO: Cloning cache of AxisArrays from https://github.com/JuliaArrays/AxisArrays.jl.git
INFO: Cloning cache of CategoricalArrays from https://github.com/JuliaData/CategoricalArrays.jl.git
INFO: Cloning cache of Combinatorics from https://github.com/JuliaMath/Combinatorics.jl.git
INFO: Cloning cache of IntervalSets from https://github.com/JuliaMath/IntervalSets.jl.git
INFO: Cloning cache of NamedArrays from https://github.com/davidavdav/NamedArrays.jl.git
INFO: Cloning cache of NullableArrays from https://github.com/JuliaStats/NullableArrays.jl.git
INFO: Cloning cache of Nulls from https://github.com/JuliaData/Nulls.jl.git
INFO: Cloning cache of Polynomials from https://github.com/JuliaMath/Polynomials.jl.git
INFO: Cloning cache of RCall from https://github.com/JuliaInterop/RCall.jl.git
INFO: Cloning cache of RangeArrays from https://github.com/JuliaArrays/RangeArrays.jl.git
INFO: Installing AxisArrays v0.2.0
INFO: Installing CategoricalArrays v0.2.3
INFO: Installing Combinatorics v0.4.1
INFO: Installing IntervalSets v0.1.1
INFO: Installing NamedArrays v0.6.1
INFO: Installing NullableArrays v0.1.2
INFO: Installing Nulls v0.1.2
INFO: Installing Polynomials v0.1.6
INFO: Installing RCall v0.7.5
INFO: Installing RangeArrays v0.2.0
INFO: Building SpecialFunctions
INFO: Package database updated

In [43]:
using RCall, RDatasets

mtcars = datasets("datasets", "mtcars");
library(ggplot2)
ggplot($mtcars, aes(x = WT, y=MPG)) + geom_point()

INFO: Precompiling module RCall.
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/deeplearn/.julia/v0.6/NullableArrays/src/operators.jl:99.
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/deeplearn/.julia/v0.6/NullableArrays/src/operators.jl:99.
ERROR: LoadError: LoadError: Could not find R installation. Either set the "R_HOME" environmental variable, or ensure the R executable is available in "PATH".
Stacktrace:
 [1] locate_Rhome_libR() at /home/deeplearn/.julia/v0.6/RCall/src/setup.jl:119
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /home/deeplearn/.julia/v0.6/RCall/src/setup.jl, in expression starting on line 122
while loading /home/deeplearn/.julia/v0.6/RCall/src/RCall.jl, in expression starting on line 29

LoadError: Failed to precompile RCall to /home/deeplearn/.julia/lib/v0.6/RCall.ji.